spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testbars
    username: sa
    password:

logging:
  level:
    root: WARN
    com.github.nvgrig.testbars: DEBUG
